### ISSUE TITLE
Resolve timer stop early issue

### ISSUE THREAD

**Issue by yatw** [cherylli/pomodoro-kotlin#27]
Currently in timer service I use +1 the intended count down time to prevent service finish before the timer in our class reaches 0. Ideally, we want both the service and timer class minus one second on every tick so they reach 0 at the same time, but the Android CountDownTimer seems to always count faster.

In 1 minute, the different sometime is ~1s, in 2 minute, the different is ~2s.. more time larger the distance. 

This is a problem within the Android CountDownTimer. My idea is to set service to count Integer.MAX_VALUE so it ensure service will not finish before our timer.

**Comment by yatw** [comment]
Just realize there is really no need to use Long for timer, lets say our session can support up to 2 days, (2 * 24 * 60 * 60 * 1000) is only 172800000, which is still within Integer.MAX_VALUE's 2147483647.

**Comment by cherylli** [comment]
yeah that makes sense. pomodoro timers rarely go past 30mins anyway, i think.

**Comment by yatw** [comment]
That was not the only problem making the timer stopping, it turns out Android OS will kill the service on low memory. Service was meant to be killed and has the ability to resume from their previous state.

Problem description:
https://stackoverflow.com/questions/12219249/background-service-getting-killed-in-android

Possible solution is to turn it into foreground service
https://stackoverflow.com/questions/30624019/android-what-is-the-difference-between-a-foreground-and-background-service

**Comment by yatw** [comment]
To reproduce the timer stop early issue, set ~5 minute and close the phone. It will likely stop.

**Comment by yatw** [comment]
Issue addressed on README
